### ISSUE TITLE
🐛 [BUG] - Table not found when trying to change username

### ISSUE THREAD

**Issue by MerlinB** [undb-io/undb#2131]
### Description

I went to the user settings and tried to change my name with the application crashing as a result.
I am self-hosting via docker and disabled the authentication flow.

### Reproduction steps

```bash
1. Disable auth flow, use admin email and password env vars
2. Go to user settings
3. Try to change your name
```

### Logs

```bash
undb  | {"level":30,"time":1731187745505,"pid":7,"hostname":"9d6565ce95ea","module":"Auth","method":"GET","query":{},"path":"/api/me","requestId":"b1155295-dd44-43c7-9aa8-3c9c5cdfbec8","msg":"openapi request"}
undb  | ERR 116 |     expect(msg) {
undb  | 117 |         if (this[common_1.T]) {
undb  | 118 |             return this[common_1.Val];
undb  | 119 |         }
undb  | 120 |         else {
undb  | 121 |             throw new Error(msg);
undb  |                             ^
undb  | GraphQLError: not found table
undb  |       at expect (/usr/src/app/node_modules/oxide.ts/dist/option.js:121:23)
undb  |       at processTicksAndRejections (native:7:39)
undb  | 
undb  | ERR 116 |     expect(msg) {
undb  | 117 |         if (this[common_1.T]) {
undb  | 118 |             return this[common_1.Val];
undb  | 119 |         }
undb  | 120 |         else {
undb  | 121 |             throw new Error(msg);
undb  |                             ^
undb  | GraphQLError: not found table
undb  |       at expect (/usr/src/app/node_modules/oxide.ts/dist/option.js:121:23)
undb  |       at processTicksAndRejections (native:7:39)
```

**Comment by MerlinB** [comment]
I realised that the logged errors are probably unrelated to this - they pop up regularly and are caused by a query that looks for a table in the wrong space.

**Comment by nichenqin** [comment]
Currently unable to reproduce, it may be affected by certain settings. Will try other reproduction steps.

**Comment by sokai** [comment]
+1 – nothing to see with `LOG_LEVEL=debug`, the app _freezes_ somehow (and after a container restart the username is unchanged = the old/initial one, `tables`) … :/ KR
